# Generated by Django 4.1 on 2022-12-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='slogan',
            field=models.TextField(default="Your best choice when you're on the lookup for NFTs."),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title',
            field=models.CharField(default='The #1 source for NFT lookup', max_length=1000),
        ),
        migrations.AlterField(
            model_name='settings',
            name='trade_mark',
            field=models.CharField(default='NFT LOOKUP', max_length=225),
        ),
    ]
